version: 2
jobs:
  docs:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/EpicBanItemDocs
    steps:
      - checkout:
          path: ~/EpicBanItemDocs
      - run: find . -name "*.md" ! -name "SUMMARY.md" | tee files
      - run: npm install --force --save-prod --verbose markdownlint-cli
      - run: xargs node node_modules/markdownlint-cli/markdownlint.js <files
workflows:
  version: 2
  build:
    jobs:
      - docs:
          filters:
            branches:
              only: gh-pages
