version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/EpicBanItem
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout:
          path: ~/EpicBanItem
      - restore_cache:
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew clean build -Psigning.password=$SIGNING_PASSWORD
      - store_artifacts:
          path: build/libs
