name: Build and Publish
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.ACTIONS_COMMIT }}

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: microsoft

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Test and Build
        run: ./gradlew test build -Dsemver.overrideVersion=${{ github.ref_name }}

      - name: Determinate latest released tag
        id: current-tag
        run: |
          tag=$(git describe --tags --abbrev=0 --match 'v*');
          echo "::set-output name=tag::$tag";      

      - name: Get semver
        id: semver
        run: |
          ./gradlew generateVersionFile -Dsemver.overrideVersion={{ github.ref_name }}
          echo "::set-output name=version::$(tail -1 build/semver/version.txt)"

      - uses: seasonalmatcha/conventional-commit-changelog@latest
        id: changelog
        with:
          from: ${{ steps.current-tag.outputs.tag }}
          to: ${{ steps.semver.outputs.version }}

#      - name: Prepend Changelog
#        if: steps.changelog.outputs.changelog != 'No Changes'
#        uses: endaft/action-prepend@v0.0.9
#        with:
#          file_target: CHANGELOG.md
#          value_in: ${{ format('# {0}\n{1}\n', steps.tag.outputs.version, steps.changelog.outputs.changelog) }}
#          is_file: "false"

      - uses: actions/upload-artifact@v3
        if: steps.changelog.outputs.changelog != 'No Changes'
        with:
          name: plugin
          path: build/libs/EpicBanItem-${{ steps.semver.outputs.version }}.jar
          if-no-files-found: error

      - name: Upload to Ore
        if: steps.changelog.outputs.changelog != 'No Changes'
        uses: dualspiral/ore-upload-action@v2
        with:
          plugin: plugin
          description: ${{ steps.changelog.outputs.changelog }}
          apiKey: ${{ secrets.ORE_API_KEY }}
          pluginId: epicbanitem