name: Build and Publish
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: microsoft

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Test and Build
        run: ./gradlew test build

      - name: Determinate latest released tag
        id: current-tag
        run: |
          tag=$(git describe --tags --abbrev=0 --match 'v*');
          echo "::set-output name=tag::$tag";      

      - name: Create tag
        id: tag
        run: |
          ./gradlew generateVersionFile
          echo "::set-output name=version::$(tail -1 build/semver/version.txt)"
          ./gradlew createAndPushVersionTag

      - uses: seasonalmatcha/conventional-commit-changelog@latest
        id: changelog
        with:
          from: ${{ steps.current-tag.outputs.tag }}
          to: ${{ steps.tag.outputs.version }}

      - name: Prepend Changelog
        uses: endaft/action-prepend@v0.0.9
        with:
          file_target: CHANGELOG.md
          value_in: ${{ format('# {0}\n{1}\n', steps.tag.outputs.version, steps.changelog.outputs.body) }}
          is_file: "false"

      - uses: actions/upload-artifact@v3
        if: steps.changelog.outputs.body
        with:
          name: plugin
          path: build/libs/EpicBanItem-${{ steps.current-tag.outputs.tag }}.jar
          if-no-files-found: error

      - name: Upload to Ore
        if: steps.changelog.outputs.body
        uses: dualspiral/ore-upload-action@v2
        with:
          plugin: plugin
          description: ${{ steps.changelog.outputs.body }}
          apiKey: ${{ secrets.ORE_API_KEY }}
          pluginId: epicbanitem