name: Tag and Release
on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: microsoft

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Determinate latest released tag
        id: current-tag
        run: |
          tag=$(git describe --tags --abbrev=0 --match 'v*');
          echo "::set-output name=tag::$tag";      

      - name: Create tag
        id: tag
        run: |
          ./gradlew generateVersionFile
          echo "::set-output name=version::$(tail -1 build/semver/version.txt)"
          ./gradlew createAndPushVersionTag

      - uses: seasonalmatcha/conventional-commit-changelog@latest
        id: changelog
        with:
          from: ${{ steps.current-tag.outputs.tag }}
          to: ${{ steps.tag.outputs.version }}

      - name: Test and Build
        if: steps.changelog.outputs.changelog
        run: ./gradlew test build

      - name: Create Release
        if: steps.changelog.outputs.changelog
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          tag: ${{ steps.tag.outputs.version }}
          body: ${{ steps.changelog.outputs.changelog }}
          token: ${{ github.token }}
          artifacts: build/libs/EpicBanItem-*.jar