name: Release
on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.ACTIONS_COMMIT }}

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: microsoft

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Test and Build
        run: ./gradlew test build -Psemver.overrideVersion=${{ github.ref_name }}

      - name: Get the version
        id: version
        run: echo ::set-output name=version::$(echo ${{ github.ref_name }} | cut -c2-)

      - name: Filter not beta
        id: not-beta
        run: if [[ $GITHUB_REF =~ v[0-9]+\.[0-9]+\.[0-9]+-?.* ]]; then echo "::set-output name=result::true"; fi

      - name: Get prev tag
        id: prev-tag
        run: |
          if [[ ${{ steps.not-beta.outputs.result }} = true ]]; 
          then echo "::set-output name=tag::$(git describe --abbrev=0 --tags $(git describe --abbrev=0)^ --match 'v[0-9]*')";
          else echo "::set-output name=tag::$(git describe --abbrev=0 --tags $(git describe --abbrev=0)^ --match 'v[0-9]*' --exclude *-*)";
          fi

      - uses: seasonalmatcha/conventional-commit-changelog@latest
        id: changelog
        with:
          from: ${{ steps.prev-tag.outputs.tag }}
          to: ${{ github.ref_name }}

      - name: Create Release
        if: steps.changelog.outputs.changelog != 'No Changes'
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          tag: ${{ github.ref_name }}
          body: ${{ steps.body.outputs.content }}
          token: ${{ github.token }}
          artifacts: build/libs/EpicBanItem-${{ steps.version.outputs.version }}.jar
          artifactErrorsFailBuild: true