name: Tag and Release
on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: microsoft

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Test
        run: ./gradlew test

      - name: Build
        run: ./gradlew build

      - name: Create tag
        id: tag
        run: |
          ./gradlew createAndPushVersionTag
          ./gradlew generateVersionFile
          echo "::set-output name=version::$(tail -1 build/semver/version.txt)"

      - name: Generate Changelog
        id: changelog
        uses: Requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ steps.tag.outputs.version }}
          writeToFile: false
          excludeTypes: build,docs,other,style,ci

#      - name: Find Tag
#        id: tagger
#        uses: jimschubert/query-tag-action@v1
#        with:
#          include: v[0-9]+.[0-9]+.[0-9]+

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          tag: ${{ steps.tag.outputs.version }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}
          artifacts: build/libs/EpicBanItem*