name: Tag and Release
on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.ACTIONS_COMMIT }}

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: microsoft

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Test and Build
        run: ./gradlew test build

      - name: Determinate latest released tag
        id: current-tag
        run: |
          tag=$(git describe --tags --abbrev=0 --match 'v*');
          echo "::set-output name=tag::$tag";  

      - name: Get semver
        id: semver
        run: |
          ./gradlew generateVersionFile
          echo "::set-output name=version::$(head -1 build/semver/version.txt)"

      - name: Tag
        run: |
          tag=v${{ steps.semver.outputs.version }}
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -a "${tag}"
          git push origin "${tag}"

      - uses: seasonalmatcha/conventional-commit-changelog@latest
        id: changelog
        with:
          from: ${{ steps.current-tag.outputs.tag }}
          to: v${{ steps.semver.outputs.version }}

      - name: Create Release
        if: steps.changelog.outputs.changelog != 'No Changes'
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          tag: v${{ steps.semver.outputs.version }}
          body: ${{ steps.changelog.outputs.changelog }}
          token: ${{ github.token }}
          artifacts: build/libs/EpicBanItem-${{ steps.semver.outputs.version }}.jar
          artifactErrorsFailBuild: true