name: Test latest Gradle
on:
  schedule:
    - cron: 0 0 * * 0 # weekly
jobs:
  gradle-rc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: 16
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
      - run: gradle build --dry-run # just test build configuration