name: Test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.ACTIONS_COMMIT }}

      - uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: microsoft

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Filter ref
        id: ref
        run: if [[ $GITHUB_REF =~ "v[0-9]+\.[0-9]+\.[0-9]+" ]]; then echo "::set-output name=success::true"; fi

      - name: Test on tag
        if: steps.ref.outputs.success
        run: ./gradlew test -Psemver.overrideVersion={{ github.ref_name }}

      - name: Test
        if: ${{ !steps.ref.outputs.success }}
        run: ./gradlew test